# jpa
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

# devtools
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
# docker
spring.docker.compose.lifecycle-management=start-and-stop

# db
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:ddl.sql

spring.config.import=application-jwt.properties
